# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-G4xpBfxekEBnKFhGo9TdiYbvr1UXZU
"""

def count_unique_words(filename):
    word_counts = {}  # 初始化一個空字典，用於存儲詞彙計數

    # 打開指定的文件並讀取
    with open(filename, 'r', encoding='utf-8') as file:
        for line in file:
            # 將每一行拆分成單詞
            words = line.strip().split()
            for word in words:
                # 檢查字典中是否已經存在該詞彙，如果存在，則將該詞彙的計數值加1，否則將詞彙添加到字典中並設置計數為1
                word_counts[word] = word_counts.get(word, 0) + 1

    return word_counts

def main():
    filename = "hw2_data.txt"
    # 統計詞彙出現次數
    word_counts = count_unique_words(filename)

    # 輸出
    print("總共有 {} 種不重複的詞".format(len(word_counts)))
    print("每個詞出現的次數:")
    for word, count in word_counts.items():
        print("{}: {}".format(word, count))

if __name__ == "__main__":
      main()